### ISSUE TITLE
backend profile implementation

### ISSUE THREAD

**Issue by ezronis** [TheWITProject/CentershipApp#20]
**User Story**
As a newly signed up user of the Centership Webapp, I would like to fill out my profile so that I can share my information with the community as a mentor or a mentee.

**Acceptance Criteria:** 
- Defined list of data captured about each user (for both Mentor and Mentee)
- Models for Mentor and Mentee
- Flows from signup process --> registration or profile creation

**Definition of Done**
- User can do registration/profile creation after signup
- User can Create AND Update their profile
- Profile data is visible in django admin AND postrgres

**Comment by sumaiyamahin** [comment]
- need to make 2 html files (mentor and mentee profile pages, mentor_profile.html and mentee_profile.html)
- need to add 2 more forms to forms.py that will take in information specific to the user type's profile (i.e. goals list for mentee) and create the corresponding model in the database (i.e. for forms.save it needs to be Mentor or Mentee, not User)
- update Mentor and Mentee model fields
- add the views for the two html pages in views.py
- consolidate the new mentor and new mentee forms to one function in forms.py
AFTER ALL THAT
- make 2 landing pages thats going to actually show the actual profiles of the users 
- (research if we can make 1 profile page for both user types)
